### PR TITLE
Custom password generator + Alphaspace Type

### LINKED ISSUE #3: Addition of space character for password generator

### PR DESCRIPTION
**Pull request by miranyx**
Hello,

With this pull request I implement a password generator so, new types can be added more easily. The main focus for this was to fix #3. 
This pull request also contains the code to fix that issue.

### CODE REVIEW

**Comment by cyb3rko** [comment]
Hi Benni,
thanks for your contribution. I will soon take a look at it.

I tend to replacing the input field for Password types with checkboxes of what to include into the password.
Then we would not need hardcoded types like Alphanumeric and Alphaspace.

Just like what Bitwarden does:

**Comment by cyb3rko** [comment]
But I'll first merge your PR and include it seperately I think.

**Comment by miranyx** [comment]
Do you want to implement check boxes only for the passwords or also for the passphrase?

**Comment by cyb3rko** [comment]
There are no settings for the passphrase generation except the length.
So check boxes would not really make sense there.

**Comment by miranyx** [comment]
There are settings for passphrases in the linux desktop client for bitwarden.
20230423_16h43m59s_grim

**Comment by cyb3rko** [comment]
Yeah, but Pazzword uses the nbvcxz passphrase generator, which does not support those settings.

**Pull request merged**
